# This file was generated by GoReleaser. DO NOT EDIT.
cask "apple-calendar-server" do
  name "apple-calendar-server"
  desc "http server for apple calendars."
  homepage "https://github.com/legnoh/apple-calendar-server"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apple-calendar-server"
  depends_on formula: [
      "apple-calendar-cli",
    ]

  on_macos do
    on_intel do
      url "https://github.com/legnoh/apple-calendar-server/releases/download/#{version}/apple-calendar-server_#{version}_darwin_amd64.tar.gz"
      sha256 "918c71ba313b83dc2ed1ccb937d8db04e7e183541ff68ac5cff7d0afff3c45db"
    end
    on_arm do
      url "https://github.com/legnoh/apple-calendar-server/releases/download/#{version}/apple-calendar-server_#{version}_darwin_arm64.tar.gz"
      sha256 "8dc179a4d8912452849bf0d4ae3f03e863151c79fb578b1a0a2cdcfd80e16f25"
    end
  end

  caveats do
    "Please check usage at README:"
    "    https://github.com/legnoh/apple-calendar-server/blob/main/README.md"
  end

  service "run [opt_bin/"apple-calendar-server", "serve"]
keep_alive true
log_path var/"log/apple-calendar-server.log"
error_log_path var/"log/apple-calendar-server.log"
"

  # No zap stanza required
end
