# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AppleCalendarServer < Formula
  desc "http server for apple calendars.

"
  homepage "https://github.com/legnoh/apple-calendar-server"
  version "0.0.16"
  license "MIT"

  depends_on "apple-calendar-cli" if OS.mac?
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/legnoh/apple-calendar-server/releases/download/0.0.16/apple-calendar-server_0.0.16_darwin_amd64.tar.gz"
    sha256 "b1086aa3d485a378a9f8e25e8723e6ca71ca61fabbecdcb71b7d8a549fcdfb19"

    define_method(:install) do
      bin.install "apple-calendar-server"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/legnoh/apple-calendar-server/releases/download/0.0.16/apple-calendar-server_0.0.16_darwin_arm64.tar.gz"
    sha256 "54fbc9627019d1ad043a2f200d7c0412ce2ed4a2fb84e821c0ff0a10d47ed8b1"

    define_method(:install) do
      bin.install "apple-calendar-server"
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/apple-calendar-server/blob/main/README.md
    EOS
  end

  service do
    run [opt_bin/"apple-calendar-server", "serve"]
    keep_alive true
    log_path var/"log/apple-calendar-server.log"
    error_log_path var/"log/apple-calendar-server.log"
  end

  test do
    system "#{bin}/apple-calendar-server --help"
  end
end
