# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AppleCalendarServer < Formula
  desc "http server for apple calendars.

"
  homepage "https://github.com/legnoh/apple-calendar-server"
  version "0.0.4"
  license "MIT"

  depends_on "apple-calendar-cli" if OS.mac?
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/legnoh/apple-calendar-server/releases/download/0.0.4/apple-calendar-server_0.0.4_darwin_amd64.tar.gz"
    sha256 "c39c274e90c460ab535975a11d17eb9e917a4a9da52be7a6fc7f20c375ea3a06"

    def install
      bin.install "apple-calendar-server"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/legnoh/apple-calendar-server/releases/download/0.0.4/apple-calendar-server_0.0.4_darwin_arm64.tar.gz"
    sha256 "32566994e6bb3b3077d0ec3b721bfd053d44f6ed6a38e3bcd60c2a16f4feca91"

    def install
      bin.install "apple-calendar-server"
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/apple-calendar-server/blob/main/README.md
    EOS
  end

  service do
    run [opt_bin/"apple-calendar-server", "serve"]
    keep_alive true
    log_path var/"log/apple-calendar-server.log"
    error_log_path var/"log/apple-calendar-server.log"
  end

  test do
    system "#{bin}/apple-calendar-server --help"
  end
end
