# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FocusCli < Formula
  desc "Get macOS Focus mode via CLI\n"
  homepage "https://github.com/legnoh/focus-cli"
  version "0.0.43"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/legnoh/focus-cli/releases/download/0.0.43/focus-cli_0.0.43_darwin_amd64.tar.gz"
    sha256 "8dab49ce5486271b9c1b32c3a82e7827c27cfc7a517cfc792a9d18096f582626"

    define_method(:install) do
      bin.install "focus"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/legnoh/focus-cli/releases/download/0.0.43/focus-cli_0.0.43_darwin_arm64.tar.gz"
    sha256 "2839f7d2a57fd20306bbd291d4d07d07cb6e9bd83bdefacbeee715be3a94d289"

    define_method(:install) do
      bin.install "focus"
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/focus-cli/blob/main/README.md
    EOS
  end

  test do
    system "#{bin}/focus --help"
  end
end
