# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FocusCli < Formula
  desc "Get macOS Focus mode via CLI
"
  homepage "https://github.com/legnoh/focus-cli"
  version "0.0.15"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/legnoh/focus-cli/releases/download/0.0.15/focus-cli_0.0.15_darwin_amd64.tar.gz"
    sha256 "4d019769bc90fb9aadf60e997565e47b119b52e9057629521f5130b55ad26954"

    def install
      bin.install "focus"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/legnoh/focus-cli/releases/download/0.0.15/focus-cli_0.0.15_darwin_arm64.tar.gz"
    sha256 "9f1c8347e2335e66bac9b5a7823911defef2f407ca352e44025d1ecf430e878e"

    def install
      bin.install "focus"
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/focus-cli/blob/main/README.md
    EOS
  end

  test do
    system "#{bin}/focus --help"
  end
end
