# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FocusCli < Formula
  desc "Get macOS Focus mode via CLI
"
  homepage "https://github.com/legnoh/focus-cli"
  version "0.0.37"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/legnoh/focus-cli/releases/download/0.0.37/focus-cli_0.0.37_darwin_amd64.tar.gz"
    sha256 "8e790be188492369c13e6e3225318e9be4376dcbffd7b9f118f77ff3f8af5547"

    define_method(:install) do
      bin.install "focus"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/legnoh/focus-cli/releases/download/0.0.37/focus-cli_0.0.37_darwin_arm64.tar.gz"
    sha256 "86f6cfab6faa1f9e73afcb4c60d8c0573fb813e3b2877c4a1df64c78841eb5c1"

    define_method(:install) do
      bin.install "focus"
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/focus-cli/blob/main/README.md
    EOS
  end

  test do
    system "#{bin}/focus --help"
  end
end
