# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gchls < Formula
    desc "This app provides greenchannel stream url."
    homepage "https://github.com/legnoh/gchls"
    version "1.0.1"
    license "MIT"
  
    on_macos do
        url "https://github.com/legnoh/gchls/releases/download/v#{version}/gchls-v#{version}.tar.gz"
  
        def install
          bin.install "gchls"
        end
    end
  
    def caveats
      <<~EOS
        Please check usage at README:
            https://github.com/legnoh/gchls/blob/main/README.md
      EOS
    end
  
    test do
      system "#{bin}/gchls --help"
    end
  end
