# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoogleCalendarIcsFixer < Formula
  desc "google calendar ics fixer\n\n"
  homepage "https://github.com/legnoh/google-calendar-ics-fixer"
  version "0.0.23"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/legnoh/google-calendar-ics-fixer/releases/download/0.0.23/google-calendar-ics-fixer_0.0.23_darwin_amd64.tar.gz"
    sha256 "27a950a7d9a663a99cd2ed5d299e24d47e8a940ad34ba12982b712ee326aa882"

    define_method(:install) do
      bin.install "google-calendar-ics-fixer"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/legnoh/google-calendar-ics-fixer/releases/download/0.0.23/google-calendar-ics-fixer_0.0.23_darwin_arm64.tar.gz"
    sha256 "bfa0174cb6d2ba79f3bc146d323c18f871e843e58ea968442753dedfad716306"

    define_method(:install) do
      bin.install "google-calendar-ics-fixer"
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/google-calendar-ics-fixer/blob/main/README.md
    EOS
  end

  test do
    system "#{bin}/google-calendar-ics-fixer --help"
  end
end
