# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoogleCalendarIcsFixer < Formula
  desc "google calendar ics fixer

"
  homepage "https://github.com/legnoh/google-calendar-ics-fixer"
  version "0.0.20"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/legnoh/google-calendar-ics-fixer/releases/download/0.0.20/google-calendar-ics-fixer_0.0.20_darwin_amd64.tar.gz"
    sha256 "acfdb975623c0d124f35bbd61147e75a74f3df5dca83cbcbe966c40368854bab"

    define_method(:install) do
      bin.install "google-calendar-ics-fixer"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/legnoh/google-calendar-ics-fixer/releases/download/0.0.20/google-calendar-ics-fixer_0.0.20_darwin_arm64.tar.gz"
    sha256 "3e4e3a58a5e0c674f2c40673609fac3bd49860ad02083b3291903f1468f82279"

    define_method(:install) do
      bin.install "google-calendar-ics-fixer"
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/google-calendar-ics-fixer/blob/main/README.md
    EOS
  end

  test do
    system "#{bin}/google-calendar-ics-fixer --help"
  end
end
