# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoogleCalendarIcsFixer < Formula
  desc "google calendar ics fixer

"
  homepage "https://github.com/legnoh/google-calendar-ics-fixer"
  version "0.0.10"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/legnoh/google-calendar-ics-fixer/releases/download/0.0.10/google-calendar-ics-fixer_0.0.10_darwin_amd64.tar.gz"
    sha256 "f52c91099763cfdf93aa52da2d4aee00a65e90fcbfef9e9d2121fea1d116fe47"

    define_method(:install) do
      bin.install "google-calendar-ics-fixer"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/legnoh/google-calendar-ics-fixer/releases/download/0.0.10/google-calendar-ics-fixer_0.0.10_darwin_arm64.tar.gz"
    sha256 "cf3272d590aab93f46f434ee38337e86d47e4614881168c9ad7a35a3bb3150c9"

    define_method(:install) do
      bin.install "google-calendar-ics-fixer"
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/google-calendar-ics-fixer/blob/main/README.md
    EOS
  end

  test do
    system "#{bin}/google-calendar-ics-fixer --help"
  end
end
