# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HapNatureRemo < Formula
  desc "This app provides homekit virtual devices defined by Nature Remo."
  homepage "https://github.com/legnoh/hap-nature-remo"
  version "0.0.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/legnoh/hap-nature-remo/releases/download/0.0.18/hap-nature-remo_0.0.18_darwin_arm64.tar.gz"
      sha256 "a345183dace8d83b3f558f5d6ebffc6acd151e5c989cada557fe8e65c715fe79"

      def install
        bin.install "hap-nature-remo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/legnoh/hap-nature-remo/releases/download/0.0.18/hap-nature-remo_0.0.18_darwin_amd64.tar.gz"
      sha256 "9d3b7b5b497637722741258a3077b312f7508a87eefb8595bb04fb398bfcadf8"

      def install
        bin.install "hap-nature-remo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/legnoh/hap-nature-remo/releases/download/0.0.18/hap-nature-remo_0.0.18_linux_arm64.tar.gz"
      sha256 "816388f3c033d4f493303a113f082e8fb4984404979aa2358ba18e7ee9a59601"

      def install
        bin.install "hap-nature-remo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/legnoh/hap-nature-remo/releases/download/0.0.18/hap-nature-remo_0.0.18_linux_amd64.tar.gz"
      sha256 "d5364b2ab8183cc21ebe08fb1fa5179868c949f1a9d85f84c93a6ffafe85a9dd"

      def install
        bin.install "hap-nature-remo"
      end
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/hap-nature-remo/blob/main/README.md
    EOS
  end

  service do
    run [opt_bin/"hap-nature-remo", "serve"]
    keep_alive true
    log_path var/"log/hap-nature-remo.log"
    error_log_path var/"log/hap-nature-remo.log"
  end

  test do
    system "#{bin}/hap-nature-remo --help"
  end
end
