# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HapSwitchCommand < Formula
  desc "This app provides homekit virtual switch devices executing local commands.
"
  homepage "https://github.com/legnoh/hap-switch-command"
  version "0.0.61"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/legnoh/hap-switch-command/releases/download/0.0.61/hap-switch-command_0.0.61_darwin_amd64.tar.gz"
      sha256 "fae0b47e4c0160115aaebdc347a8f023e5a61c49fb9e2293ebb3c6cbda64810a"

      define_method(:install) do
        bin.install "hap-switch-command"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/legnoh/hap-switch-command/releases/download/0.0.61/hap-switch-command_0.0.61_darwin_arm64.tar.gz"
      sha256 "623c86c11a139f7cd2a192a69e2625e051accb9fbac3c90855aec72bd398cd44"

      define_method(:install) do
        bin.install "hap-switch-command"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/legnoh/hap-switch-command/releases/download/0.0.61/hap-switch-command_0.0.61_linux_amd64.tar.gz"
      sha256 "90aed0ef6f16bab0714c8a752a34c500259c3238c78e4cfe47ee5f5195422353"
      define_method(:install) do
        bin.install "hap-switch-command"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/legnoh/hap-switch-command/releases/download/0.0.61/hap-switch-command_0.0.61_linux_arm64.tar.gz"
      sha256 "bdd46cc148dad0385194d8437bd984fb46baa0553a4719e1b054d94d7fd8132c"
      define_method(:install) do
        bin.install "hap-switch-command"
      end
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/hap-switch-command/blob/main/README.md
    EOS
  end

  service do
    run [opt_bin/"hap-switch-command", "serve"]
    keep_alive true
    log_path var/"log/hap-switch-command.log"
    error_log_path var/"log/hap-switch-command.log"
  end

  test do
    system "#{bin}/hap-switch-command --help"
  end
end
