# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HapNatureRemo < Formula
  desc "This app provides homekit virtual devices defined by Nature Remo."
  homepage "https://github.com/legnoh/hap-nature-remo"
  version "0.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/legnoh/hap-nature-remo/releases/download/0.0.12/hap-nature-remo_0.0.12_darwin_arm64.tar.gz"
      sha256 "a07684566632a52c47f3dd096b9c92e3a77bf5a3f6dc6a0e66e2aad5f5f61fee"

      def install
        bin.install "hap-nature-remo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/legnoh/hap-nature-remo/releases/download/0.0.12/hap-nature-remo_0.0.12_darwin_amd64.tar.gz"
      sha256 "ab2e70afe48ca86cf9bf24db8e2dbf020e9d0954f5e602da7b3bb5f042e552a2"

      def install
        bin.install "hap-nature-remo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/legnoh/hap-nature-remo/releases/download/0.0.12/hap-nature-remo_0.0.12_linux_arm64.tar.gz"
      sha256 "554e47d96249e0ab078076776ed8b1d1fb4c06404f8dc3f6c9e107676f0fe0e0"

      def install
        bin.install "hap-nature-remo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/legnoh/hap-nature-remo/releases/download/0.0.12/hap-nature-remo_0.0.12_linux_amd64.tar.gz"
      sha256 "767ec4dbb983fe27758b837d922952b32f38e085ff5f7be46cea192a0e381999"

      def install
        bin.install "hap-nature-remo"
      end
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/hap-nature-remo/blob/main/README.md
    EOS
  end

  service do
    run [opt_bin/"hap-nature-remo", "serve"]
    keep_alive true
    log_path var/"log/hap-nature-remo.log"
    error_log_path var/"log/hap-nature-remo.log"
  end

  test do
    system "#{bin}/hap-nature-remo --help"
  end
end
