# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HapSwitchCommand < Formula
  desc "This app provides homekit virtual switch devices executing local commands."
  homepage "https://github.com/legnoh/hap-switch-command"
  version "0.0.24"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/legnoh/hap-switch-command/releases/download/0.0.24/hap-switch-command_0.0.24_darwin_amd64.tar.gz"
      sha256 "e195bd6eca648f181568da39f8afbe013e326f7d29b08c22b9ab3c7f37b959fb"

      def install
        bin.install "hap-switch-command"
      end
    end
    on_arm do
      url "https://github.com/legnoh/hap-switch-command/releases/download/0.0.24/hap-switch-command_0.0.24_darwin_arm64.tar.gz"
      sha256 "bfc5373cdedee5b5ce3bbb664cade48c218fb98ef6503b084adc7eb8a4b9b437"

      def install
        bin.install "hap-switch-command"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/legnoh/hap-switch-command/releases/download/0.0.24/hap-switch-command_0.0.24_linux_amd64.tar.gz"
        sha256 "0906a05660008deed1d8b414d279b100e3cd8e96a7053819856f9e11c3fe4c94"

        def install
          bin.install "hap-switch-command"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/legnoh/hap-switch-command/releases/download/0.0.24/hap-switch-command_0.0.24_linux_arm64.tar.gz"
        sha256 "802c6e39bde67920f3019b6bf55ca370c0931893885fc7c27d5c4077c47ef479"

        def install
          bin.install "hap-switch-command"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/hap-switch-command/blob/main/README.md
    EOS
  end

  service do
    run [opt_bin/"hap-switch-command", "serve"]
    keep_alive true
    log_path var/"log/hap-switch-command.log"
    error_log_path var/"log/hap-switch-command.log"
  end

  test do
    system "#{bin}/hap-switch-command --help"
  end
end
