# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HapSwitchCommand < Formula
  desc "This app provides homekit virtual switch devices executing local commands.
"
  homepage "https://github.com/legnoh/hap-switch-command"
  version "0.0.31"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/legnoh/hap-switch-command/releases/download/0.0.31/hap-switch-command_0.0.31_darwin_amd64.tar.gz"
      sha256 "99efc1ce559596ca18468affe838864089dcf60b936e3b92f5ef846a5a4ecbba"

      def install
        bin.install "hap-switch-command"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/legnoh/hap-switch-command/releases/download/0.0.31/hap-switch-command_0.0.31_darwin_arm64.tar.gz"
      sha256 "d4fb09e0a72b719d26e4e629be4069139d04305f39b3c11eb6c2d3114497e0d2"

      def install
        bin.install "hap-switch-command"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/legnoh/hap-switch-command/releases/download/0.0.31/hap-switch-command_0.0.31_linux_amd64.tar.gz"
        sha256 "67b567744ce3015617a50190fc48265a4835f11e910c03207c7b0d460a84ce89"

        def install
          bin.install "hap-switch-command"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/legnoh/hap-switch-command/releases/download/0.0.31/hap-switch-command_0.0.31_linux_arm64.tar.gz"
        sha256 "b7686068bb7bc633f3a42ced5c5f0020918585ed9580565526aca3207bd81f45"

        def install
          bin.install "hap-switch-command"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/hap-switch-command/blob/main/README.md
    EOS
  end

  service do
    run [opt_bin/"hap-switch-command", "serve"]
    keep_alive true
    log_path var/"log/hap-switch-command.log"
    error_log_path var/"log/hap-switch-command.log"
  end

  test do
    system "#{bin}/hap-switch-command --help"
  end
end
