# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HapNatureRemo < Formula
  desc "This app provides homekit virtual devices defined by Nature Remo."
  homepage "https://github.com/legnoh/hap-nature-remo"
  version "0.0.21"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/legnoh/hap-nature-remo/releases/download/0.0.21/hap-nature-remo_0.0.21_darwin_arm64.tar.gz"
      sha256 "119ef39c170985eaf8517d007dd81411ccba9b4fca0fd5a9f9fa695d95d5fd76"

      def install
        bin.install "hap-nature-remo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/legnoh/hap-nature-remo/releases/download/0.0.21/hap-nature-remo_0.0.21_darwin_amd64.tar.gz"
      sha256 "2cf52ec608af2a9b5af414ecf3f454384881c4ef2d3b9e39d110a4cff0441c45"

      def install
        bin.install "hap-nature-remo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/legnoh/hap-nature-remo/releases/download/0.0.21/hap-nature-remo_0.0.21_linux_arm64.tar.gz"
      sha256 "fc65b742f5fa11b792f464ee527d85b466ce105914bc2381c5e12f4c086a2acd"

      def install
        bin.install "hap-nature-remo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/legnoh/hap-nature-remo/releases/download/0.0.21/hap-nature-remo_0.0.21_linux_amd64.tar.gz"
      sha256 "4161666ae4496f4e649615a5df10f738463cf2cec335602138b51aca75dd23c3"

      def install
        bin.install "hap-nature-remo"
      end
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/hap-nature-remo/blob/main/README.md
    EOS
  end

  service do
    run [opt_bin/"hap-nature-remo", "serve"]
    keep_alive true
    log_path var/"log/hap-nature-remo.log"
    error_log_path var/"log/hap-nature-remo.log"
  end

  test do
    system "#{bin}/hap-nature-remo --help"
  end
end
