# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ImmichImporter < Formula
  desc "This app is a daemon that converts Reminders.app data into metrics in Prometheus Exporter format and provides them.\n"
  homepage "https://github.com/legnoh/immich-importer"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/legnoh/immich-importer/releases/download/0.0.8/immich-importer_0.0.8_darwin_amd64.tar.gz"
      sha256 "f0c4565a0a52bb8aaa906a93d4423e998bce8dae3a42abfe94d3c54f6e69e508"

      define_method(:install) do
        bin.install "immich-importer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/legnoh/immich-importer/releases/download/0.0.8/immich-importer_0.0.8_darwin_arm64.tar.gz"
      sha256 "53941c47c34f7cc7077627f645df411fff8c0f4eb12dd1a438d42a57ae449bc0"

      define_method(:install) do
        bin.install "immich-importer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/legnoh/immich-importer/releases/download/0.0.8/immich-importer_0.0.8_linux_amd64.tar.gz"
      sha256 "e3cf69c8555073a3f5512e6854ebb0cb29bb3d5c5fc7b3b8750e8cc81f41bfa1"
      define_method(:install) do
        bin.install "immich-importer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/legnoh/immich-importer/releases/download/0.0.8/immich-importer_0.0.8_linux_arm64.tar.gz"
      sha256 "c378f3a4d659a413647494a69f845f42020106ee758588120da0cecba972c44a"
      define_method(:install) do
        bin.install "immich-importer"
      end
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/immich-importer/blob/main/README.md
    EOS
  end

  test do
    system "#{bin}/immich-importer --help"
  end
end
