# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ImmichImporter < Formula
  desc "This app is a daemon that converts Reminders.app data into metrics in Prometheus Exporter format and provides them.
"
  homepage "https://github.com/legnoh/immich-importer"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/legnoh/immich-importer/releases/download/0.0.1/immich-importer_0.0.1_darwin_amd64.tar.gz"
      sha256 "394728ab3dfcf429640f5db27dc521fe9d1950b82118de1e7fc7f13b1622a50d"

      define_method(:install) do
        bin.install "immich-importer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/legnoh/immich-importer/releases/download/0.0.1/immich-importer_0.0.1_darwin_arm64.tar.gz"
      sha256 "8b9abc9496b559d637d40e071b517c8d76e6b138b2051a0ba9461c41d237d01e"

      define_method(:install) do
        bin.install "immich-importer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/legnoh/immich-importer/releases/download/0.0.1/immich-importer_0.0.1_linux_amd64.tar.gz"
      sha256 "702b839f9f242961d26665be2b05c5ea90bee1a571d24c3d5b1994a01ff0161b"
      define_method(:install) do
        bin.install "immich-importer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/legnoh/immich-importer/releases/download/0.0.1/immich-importer_0.0.1_linux_arm64.tar.gz"
      sha256 "54ac73b9511ed82689e061686b2970c816789a25b3a7f0ed7cd5a10efb1e7565"
      define_method(:install) do
        bin.install "immich-importer"
      end
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/immich-importer/blob/main/README.md
    EOS
  end

  test do
    system "#{bin}/immich-importer --help"
  end
end
