# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KongBoilerplate < Formula
  desc "This app is a daemon that converts Reminders.app data into metrics in Prometheus Exporter format and provides them.
"
  homepage "https://github.com/legnoh/kong-boilerplate"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/legnoh/kong-boilerplate/releases/download/0.0.1/kong-boilerplate_0.0.1_darwin_amd64.tar.gz"
      sha256 "6a8e49205141693bde964b6069eb4587849e41c54f7a3504d4fc9829171b3773"

      define_method(:install) do
        bin.install "kong-boilerplate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/legnoh/kong-boilerplate/releases/download/0.0.1/kong-boilerplate_0.0.1_darwin_arm64.tar.gz"
      sha256 "5f8822626a2d14941353a3346503c67ffea2294bfe9390a03596db2ec64392c1"

      define_method(:install) do
        bin.install "kong-boilerplate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/legnoh/kong-boilerplate/releases/download/0.0.1/kong-boilerplate_0.0.1_linux_amd64.tar.gz"
      sha256 "9793395c04cdfbb09b9d39c77ef4a8fbfb1148d56c1c153deac79361f33ee95d"
      define_method(:install) do
        bin.install "kong-boilerplate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/legnoh/kong-boilerplate/releases/download/0.0.1/kong-boilerplate_0.0.1_linux_arm64.tar.gz"
      sha256 "dc6c280e700ee4db3482825638507f974ee004b8f6c113179a79a8ca9974ff21"
      define_method(:install) do
        bin.install "kong-boilerplate"
      end
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/kong-boilerplate/blob/main/README.md
    EOS
  end

  test do
    system "#{bin}/kong-boilerplate --help"
  end
end
