# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RemindersExporter < Formula
  desc "This app is a daemon that converts Reminders.app data into metrics in Prometheus Exporter format and provides them.\n\n"
  homepage "https://github.com/legnoh/reminders-exporter"
  version "1.0.51"
  license "MIT"

  depends_on "reminders-cli" if OS.mac?
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/legnoh/reminders-exporter/releases/download/1.0.51/reminders-exporter_1.0.51_darwin_amd64.tar.gz"
    sha256 "4b65a4845984df314a770a10281795f360c20f63b617447654190047a3dbe78c"

    define_method(:install) do
      bin.install "reminders-exporter"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/legnoh/reminders-exporter/releases/download/1.0.51/reminders-exporter_1.0.51_darwin_arm64.tar.gz"
    sha256 "77f3cd486a3d8b636076bcf6e06e75b7b2bb76c879cbf8ebd3edf450ee22a369"

    define_method(:install) do
      bin.install "reminders-exporter"
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/reminders-exporter/blob/main/README.md
    EOS
  end

  service do
    run [opt_bin/"reminders-exporter", "serve"]
    keep_alive true
    log_path var/"log/reminders-exporter.log"
    error_log_path var/"log/reminders-exporter.log"
  end

  test do
    system "#{bin}/reminders-exporter --help"
  end
end
