# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RemindersExporter < Formula
  desc "This app is a daemon that converts Reminders.app data into metrics in Prometheus Exporter format and provides them.

"
  homepage "https://github.com/legnoh/reminders-exporter"
  version "1.0.16"
  license "MIT"

  depends_on "reminders-cli" if OS.mac?
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/legnoh/reminders-exporter/releases/download/1.0.16/reminders-exporter_1.0.16_darwin_amd64.tar.gz"
    sha256 "29492ded5410a2baf3ada398d0e124ea5a06b77021c45487fa766c1b72db4b60"

    def install
      bin.install "reminders-exporter"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/legnoh/reminders-exporter/releases/download/1.0.16/reminders-exporter_1.0.16_darwin_arm64.tar.gz"
    sha256 "726e46a023407388689e31ef7aaf0142bb863ee098d73bfdc60f3689fcdff59b"

    def install
      bin.install "reminders-exporter"
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/reminders-exporter/blob/main/README.md
    EOS
  end

  service do
    run [opt_bin/"reminders-exporter", "serve"]
    keep_alive true
    log_path var/"log/reminders-exporter.log"
    error_log_path var/"log/reminders-exporter.log"
  end

  test do
    system "#{bin}/reminders-exporter --help"
  end
end
