# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RemindersExporter < Formula
  desc "This app is a daemon that converts Reminders.app data into metrics in Prometheus Exporter format and provides them."
  homepage "https://github.com/legnoh/reminders-exporter"
  version "1.0.0"
  license "MIT"

  depends_on "reminders-cli" if OS.mac?
  depends_on :macos

  on_intel do
    url "https://github.com/legnoh/reminders-exporter/releases/download/1.0.0/reminders-exporter_1.0.0_darwin_amd64.tar.gz"
    sha256 "c6d58d11127d428b6b945a2235c7ed2b10360f035f5ec2b8e995f0131692f3a6"

    def install
      bin.install "reminders-exporter"
    end
  end
  on_arm do
    url "https://github.com/legnoh/reminders-exporter/releases/download/1.0.0/reminders-exporter_1.0.0_darwin_arm64.tar.gz"
    sha256 "dc932177d968d9347f26c5de4c3468acb84e5d833d4cab0864b4f34b2200e49f"

    def install
      bin.install "reminders-exporter"
    end
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/reminders-exporter/blob/main/README.md
    EOS
  end

  service do
    run [opt_bin/"reminders-exporter", "serve"]
    keep_alive true
    log_path var/"log/reminders-exporter.log"
    error_log_path var/"log/reminders-exporter.log"
  end

  test do
    system "#{bin}/reminders-exporter --help"
  end
end
