# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StickyCli < Formula
  desc "Simple script to import sticky with macOS Stickies.app"
  homepage "https://github.com/legnoh/sticky"

  url "https://github.com/legnoh/sticky-cli/archive/refs/heads/main.tar.gz"
  version "0.0.1"

  license "MIT"
  depends_on :macos

  def install
    bin.install "sticky"
  end

  def caveats
    <<~EOS
      Please check usage at README:
          https://github.com/legnoh/sticky-cli/blob/main/README.md
    EOS
  end
end
