name: Check Update(onecomme)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  check-update:
    name: Check Update
    runs-on: ubuntu-latest
    env:
      CASK_NAME: OneComme
      CASK_ID: onecomme
    steps:
    - name: Prepare
      run: apt -y install pup
    - name: Check latest version
      run: |
          latest_version=$(curl -s "https://onecomme.com/" | pup 'p.version_FnRn > strong text{}' | tail -n 1)
          echo "latest_version=${latest_version}" >> $GITHUB_ENV
    - name: Check cask version
      run: |
          cask_version=$(grep -oE "[0-9]+(\.[0-9]+){1,2}" "Casks/${CASK_ID}.rb" | head -n 1)
          echo "cask_version=${cask_version}" >> $GITHUB_ENV
    - name: Replace
      if: env.latest_version != env.cask_version
      run: |
        # replace version name
        sed -i "s/${cask_version}.\*/${latest_version}.\*/g" "Casks/${CASK_ID}.rb"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      if: env.latest_version != env.cask_version
      with:
        delete-branch: true
        title: Update ${CASK_NAME} to ${{ env.latest_version }}
        commit-message: Update ${CASK_NAME} to ${{ env.latest_version }}
